using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum SoundTag
{
    Bgm_home,
    Bgm_going,
    Bgm_day_thief,
    Eff_digital,
    Eff_fail_01,
    Eff_object_guide_02, 
    Eff_object_guide_03,
    Eff_object_put_01,
    Eff_object_select_01,
    Eff_report_phone,
    Eff_report_ring,
    Eff_report_siren, 
    Eff_success_01,
    Eff_success_02,
    Eff_twinkkle_01,
    Eff_gunshot_1,
    Eff_gunshot_2,
    Eff_scanning,
    Eff_car_crash,
    Eff_virus_die,
    Eff_water_spray,
    Eff_soap_bubble,
    Eff_dry_car,
    Eff_Wolfoo_jump,
    Eff_Wolfoo_roi,
    Eff_fail_02,
    Eff_grass_broken,
    Eff_dog_bited,
    Eff_enemy_crying_airplane,
    Eff_cheer_smallwin,   
    Eff_close_door,    
    Eff_paper_firework_particle,    
    Eff_reward_star,
    Eff_take_photo,
    Bgm_bank_guncombat,
    Bgm_intro,
    Bgm_jail,
    Bgm_wear,
    Bgm_theif_find,
    Bgm_theif_chase,
    Bgm_bank_boss,
    Bgm_child_gohome,
    Bgm_child_takecare,
    Bgm_speed_limit,
    Bgm_speed_monstercar,
    Bgm_car_wash,
    Bgm_night_catch,
    Bgm_dog_search,
    Bgm_dog_chase,
    Bgm_suspect_hint,
    Eff_button_08,
    Eff_car_mud,
    Eff_car_water,
    Eff_car_junk,
    Eff_car_leaves,
    Eff_car_brake_02,
    Eff_witch_boring,
    Eff_witch_catched,
    Eff_witch_growl,
    Eff_witch_jail,
    Eff_witch_lol,
    Eff_witch_runout,
    Eff_witch_surprise,
    Eff_footstep_02,
    Eff_object_appear_01,
    Eff_jail_guild,
    Eff_wolfoo_crying,
    Voice_stop_warning,
    Eff_2polices_huray,
    Eff_gunmiss_02,
    Eff_wolfoo_hit,
    Eff_wolfoo_huray,
    Eff_bankthief_hit_01,
    Eff_bankthief_hit_03,
    Eff_bankthief_shoot,
    Eff_bankthief_lose,
    Eff_witch_hit,
    Eff_witch_footstep,
    Eff_witch_attack_01,
    Eff_witch_endgame,
    Eff_child_huray,
    Eff_child_playtoy,
    Eff_child_drink,
    Eff_child_eat,
    Eff_child_crying2,
    Eff_child_crying1,
    Eff_FingerPrint_Scan,
    Eff_obj_Findout,
    Eff_ship,
    Eff_train,
    Eff_mom,
    Eff_Wolfoo_coax,
    Eff_carboss_catched,
    Eff_carboss_enter,
    Eff_truckover_1,
    Eff_truckover_2,
    Eff_panther_boring,
    Eff_panther_jail,
    Eff_wash_car_out,
    Eff_wolfoo_hello,
    Eff_wolfoo_virus_joy_02,
    Eff_wolfoo_virus_joy_01,
    Eff_rhino_run,
    Eff_rhino_surprise,
    Eff_obi_escape,
    Eff_wolfoo_ahha,
    Eff_jump,
    Eff_Getskin,
    Eff_object_out,
    Eff_night_helicoper,
    Eff_rhino_bike, 
    Eff_rhino_dogchase,
    Eff_rhino_dogcatch,
    Eff_dog_sniff,
    Eff_dog_singleBark,
    Eff_dog_longleBark,
    Eff_dog_growl_01,
    Eff_find_bomb

    





}

[System.Serializable]
public class Sound
{
    public SoundTag tag;
    public AudioClip clip;
    [Range(0f, 1f)]
    public float volume;
}